### ISSUE TITLE
Runtime: Primero adaptor throws 

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/kit#146]
### User story

I am not sure what this yet, but an error comes out of the Primero adaptor:

```
aleksakrolls@MacBook-Pro-5 tmp % openfn ./getPrimeroCases.js -ia primero@2.7.0 -s ./state_primeroProd.json
[CLI] ✔ Installing packages...
[CLI] ✔ Installation complete in 2ms
[CLI] ✔ Loaded state from ./state_primeroProd.json
[CLI] ✔ Compiled job from ./getPrimeroCases.js
Primero says: '200 OK'
/private/tmp/openfn/repo/node_modules/@openfn/language-primero_2.7.0/lib/Adaptor.js:317
          console.log(`${cases.length} cases retrieved from request: ${JSON.stringify(response.request, null, 2)}`);
                               ^

TypeError: Cannot read properties of undefined (reading 'length')
    at Request._callback (/private/tmp/openfn/repo/node_modules/@openfn/language-primero_2.7.0/lib/Adaptor.js:317:32)
    at self.callback (/private/tmp/openfn/repo/node_modules/@openfn/language-primero_2.7.0/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.<anonymous> (/private/tmp/openfn/repo/node_modules/@openfn/language-primero_2.7.0/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:513:28)
    at IncomingMessage.<anonymous> (/private/tmp/openfn/repo/node_modules/@openfn/language-primero_2.7.0/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v18.12.1
```
Unsure why the new runtime would case about this. It looks like the response isn't properly handled in the adaptor:

```
const resp = tryJson(body);
const cases = resp.data;
console.log(`${cases.length} cases retrieved from request: ... `)
```

**Comment by josephjclark** [comment]
I think this is nothing to do with the runtime.

The latest primero seems to run fine on my machine (:tm:), but 2.7.0 will throw if `getCases()`  is not passed an options argument.

**Comment by josephjclark** [comment]
Closing this for now as it doesn't seem to be a problem in the runtime, but with credentials. Will re-open if need be.
