### ISSUE TITLE
Setup example fails, could not resolve "@openfn/workflow-diagram"

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/kit#2]
I assume I'm doing something wrong, but opening this up for posterity.
```
~/kit main !2 ❯ pnpm run -C examples/flow start                                            Node 16.15.0 16:45:57

> flow@1.0.0 start /Users/taylor/kit/examples/flow
> pnpm node esbuild.js

Serving "." at http://127.0.0.1:8080
✘ [ERROR] Could not resolve "@openfn/workflow-diagram"

    src/index.jsx:1:28:
      1 │ import WorkflowDiagram from "@openfn/workflow-diagram";
        ╵                             ~~~~~~~~~~~~~~~~~~~~~~~~~~

  The module "./dist/index.js" was not found on the file system:

    node_modules/@openfn/workflow-diagram/package.json:10:19:
      10 │         "default": "./dist/index.js"
         ╵                    ~~~~~~~~~~~~~~~~~

  You can mark the path "@openfn/workflow-diagram" as external to exclude it from the bundle, which
  will remove this error.

/Users/taylor/kit/node_modules/.pnpm/esbuild@0.14.42/node_modules/esbuild/lib/main.js:1611
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
src/index.jsx:1:28: ERROR: Could not resolve "@openfn/workflow-diagram"
    at failureErrorWithLog (/Users/taylor/kit/node_modules/.pnpm/esbuild@0.14.42/node_modules/esbuild/lib/main.js:1611:15)
    at /Users/taylor/kit/node_modules/.pnpm/esbuild@0.14.42/node_modules/esbuild/lib/main.js:1257:28
    at runOnEndCallbacks (/Users/taylor/kit/node_modules/.pnpm/esbuild@0.14.42/node_modules/esbuild/lib/main.js:1042:63)
    at buildResponseToResult (/Users/taylor/kit/node_modules/.pnpm/esbuild@0.14.42/node_modules/esbuild/lib/main.js:1255:7)
    at /Users/taylor/kit/node_modules/.pnpm/esbuild@0.14.42/node_modules/esbuild/lib/main.js:1364:14
    at /Users/taylor/kit/node_modules/.pnpm/esbuild@0.14.42/node_modules/esbuild/lib/main.js:674:9
    at handleIncomingPacket (/Users/taylor/kit/node_modules/.pnpm/esbuild@0.14.42/node_modules/esbuild/lib/main.js:771:9)
    at Socket.readFromStdout (/Users/taylor/kit/node_modules/.pnpm/esbuild@0.14.42/node_modules/esbuild/lib/main.js:640:7)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12) {
  errors: [
    {
      detail: undefined,
      location: {
        column: 28,
        file: 'src/index.jsx',
        length: 26,
        line: 1,
        lineText: 'import WorkflowDiagram from "@openfn/workflow-diagram";',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: {
            column: 19,
            file: 'node_modules/@openfn/workflow-diagram/package.json',
            length: 17,
            line: 10,
            lineText: '        "default": "./dist/index.js"',
            namespace: '',
            suggestion: ''
          },
          text: 'The module "./dist/index.js" was not found on the file system:'
        },
        {
          location: null,
          text: 'You can mark the path "@openfn/workflow-diagram" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "@openfn/workflow-diagram"'
    }
  ],
  warnings: []
}
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by josephjclark** [comment]
I'm gonna close this down. There's a good chance that this has been fixed - I know that the workflow-diagram example is working as of this month, and has been used by Elias and myself.

If it crops up again we'll re-open the issue and investigate.
