### ISSUE TITLE
AdaptorError `dispatchHttpRequest` could not be cloned when using language-http

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/kit#464]
The job expression is:
```js
get("https://jsonplaceholder.typicode.com/todos/1");
```

And the logs are:
```
R/T Starting job 5c52cd17-93ec-4b2a-83bb-acb504f17ae6
R/T: Intialising pipeline
R/T: Timeout set to 300000ms
R/T: [linker] loading module @openfn/language-http
R/T: [linker] Loading module @openfn/language-http from /tmp/openfn/repo/node_modules/@openfn/language-http_latest/dist/index.cjs
R/T: Resolved adaptor @openfn/language-http to version 5.0.4
R/T: Executing expression (1 operations)
R/T: Starting operation 1
R/T: Operation 1 complete in 152ms
R/T: Expression complete!
R/T: Failed job 5c52cd17-93ec-4b2a-83bb-acb504f17ae6 after 628ms
R/T: AdaptorError: function httpAdapter(config) {
return new Promise(function dispatchHttpRequest(resolvePromise, rejectPromise)...<omitted>...
} could not be cloned.
R/T: {"includeStackTrace":false,"message":"function httpAdapter(config) {\n return new Promise(function dispatchHttpRequest(resolvePromise, rejectPromise)...<omitted>...\n} could not be cloned.","name":"AdaptorError","severity":"fail","source":"runtime","type":"AdaptorError"}
R/T: Check state.errors.5c52cd17-93ec-4b2a-83bb-acb504f17ae6 for details.
```

Final state is:
```json

{
  "configuration": {},
  "data": {},
  "errors": {
    "5c52cd17-93ec-4b2a-83bb-acb504f17ae6": {
      "error": {},
      "jobId": "5c52cd17-93ec-4b2a-83bb-acb504f17ae6",
      "message": "function httpAdapter(config) {\n  return new Promise(function dispatchHttpRequest(resolvePromise, rejectPromise)...<omitted>...\n} could not be cloned.",
      "type": "AdaptorError"
    }
  }
}
```

**Comment by taylordowns2000** [comment]
I've blatted my tmp/openfn/repo and tried locking the version to 5.0.3 but same issue. Here are the logs in debug mode:
```
~/b/kit/p/ws-worker main *1 ❯ rm -rf /tmp/openfn/repo                     
~/b/kit/p/ws-worker main *1 ❯ WORKER_SECRET="<< redacted >>" pnpm start --log debug

> @openfn/ws-worker@0.2.1 start /Users/taylor/build/kit/packages/ws-worker
> ts-node-esm --transpile-only src/start.ts "--log" "debug"

[RTE] ⚠ Using default repodir
[RTE] ⚠ Set env var ENGINE_REPO_DIR to use a different directory
[RTE] ℹ repoDir set to  /tmp/openfn/repo
[RTE] ❯ Loading workers from  /Users/taylor/build/kit/packages/engine-multi/dist/worker/worker.js
[RTE] ❯ Purging workers
[SRV] ❯ engine created
[SRV] ❯ Starting server
[SRV] ✔ ws-worker salty-laws-poke listening on 2222
[SRV] ❯ Connecting to Lightning at ws://localhost:4000/worker
[SRV] ❯ Connected to worker queue socket
[SRV] ✔ Connected to Lightning at ws://localhost:4000/worker
[SRV] ℹ Starting workloop
[SRV] ❯ requesting attempt...
[SRV] ❯ pulled 1 attempts
[SRV] ❯ starting attempt 77edf391-cb90-4176-ba4d-2e2f439e1e32
[SRV] ❯ connecting to  attempt:77edf391-cb90-4176-ba4d-2e2f439e1e32
[SRV] ✔ connected to attempt:77edf391-cb90-4176-ba4d-2e2f439e1e32 {}
[SRV] ❯ converted attempt as execution plan: {
  "id": "77edf391-cb90-4176-ba4d-2e2f439e1e32",
  "initialState": "e2ae4a47-0e3c-4d72-8700-e2dc54115517",
  "start": "58f67ba4-e83d-4588-b4d1-aa5b826b0862",
  "jobs": [
    {
      "id": "f17f1718-dc2e-48e8-af14-1f994e9dc2b9",
      "next": {
        "58f67ba4-e83d-4588-b4d1-aa5b826b0862": true
      }
    },
    {
      "id": "58f67ba4-e83d-4588-b4d1-aa5b826b0862",
      "expression": "// Get started by adding operations from the API reference\nget(\"https://www.google.com\");",
      "adaptor": "@openfn/language-http@5.0.3"
    }
  ]
}
[SRV] ℹ execute...
[SRV] ❯ loading dataclip e2ae4a47-0e3c-4d72-8700-e2dc54115517
[SRV] ✔ dataclip loaded
[SRV] ❯ {}
[RTE] ❯ executing plan  77edf391-cb90-4176-ba4d-2e2f439e1e32
[RTE] ❯ Creating new repo at /tmp/openfn/repo/package.json
[RTE] ℹ Will install @openfn/language-http version 5.0.3
[SRV] ❯ requesting attempt...
[SRV] ❯ pulled 0 attempts
[RTE] ✔ Installed @openfn/language-http@5.0.3
[RTE] ✔ autoinstalled @openfn/language-http@5.0.3 in 7.876s
[RTE] ❯ Starting compilation from string
[RTE] ℹ Added import statement for @openfn/language-http
[RTE] ℹ Added export * statement for @openfn/language-http
[RTE] ❯ Compiled source:
[RTE] ❯ import { get } from "@openfn/language-http";
export * from "@openfn/language-http";
export default [get("https://www.google.com")];
[RTE] ℹ starting workflow  77edf391-cb90-4176-ba4d-2e2f439e1e32
[R/T] ♦ Starting job 58f67ba4-e83d-4588-b4d1-aa5b826b0862
[R/T] ❯ Intialising pipeline
[R/T] ❯ Timeout set to 300000ms
[R/T] ❯ [linker] loading module @openfn/language-http
[R/T] ❯ [linker] Loading module @openfn/language-http from /tmp/openfn/repo/node_modules/@openfn/language-http_5.0.3/dist/index.cjs
[R/T] ℹ Resolved adaptor @openfn/language-http to version 5.0.3
[SRV] ℹ 77edf391-cb90-4176-ba4d-2e2f439e1e32 :: attempt:start :: OK
[SRV] ℹ 77edf391-cb90-4176-ba4d-2e2f439e1e32 :: attempt:log :: OK
[SRV] ℹ 77edf391-cb90-4176-ba4d-2e2f439e1e32 :: attempt:log :: OK
[SRV] ℹ 77edf391-cb90-4176-ba4d-2e2f439e1e32 :: attempt:log :: OK
[SRV] ℹ 77edf391-cb90-4176-ba4d-2e2f439e1e32 :: attempt:log :: OK
[SRV] ℹ 77edf391-cb90-4176-ba4d-2e2f439e1e32 :: attempt:log :: OK
[SRV] ℹ 77edf391-cb90-4176-ba4d-2e2f439e1e32 :: attempt:log :: OK
[R/T] ❯ Executing expression (1 operations)
[R/T] ❯ Starting operation 1
[SRV] ℹ 77edf391-cb90-4176-ba4d-2e2f439e1e32 :: attempt:log :: OK
[SRV] ℹ 77edf391-cb90-4176-ba4d-2e2f439e1e32 :: run:start :: OK
[SRV] ℹ 77edf391-cb90-4176-ba4d-2e2f439e1e32 :: attempt:log :: OK
GET request succeeded with 200 ✓
[R/T] ℹ Operation 1 complete in 238ms
[R/T] ❯ Expression complete!
[R/T] ✘ Failed job 58f67ba4-e83d-4588-b4d1-aa5b826b0862 after 445ms
[R/T] ✘ AdaptorError: function httpAdapter(config) {
  return new Promise(function dispatchHttpRequest(resolvePromise, rejectPromise)...<omitted>...
} could not be cloned.
[R/T] ❯ {
  "source": "runtime",
  "includeStackTrace": false,
  "type": "AdaptorError",
  "name": "AdaptorError",
  "severity": "fail",
  "message": "function httpAdapter(config) {\n  return new Promise(function dispatchHttpRequest(resolvePromise, rejectPromise)...<omitted>...\n} could not be cloned."
}
[R/T] ✘ Check state.errors.58f67ba4-e83d-4588-b4d1-aa5b826b0862 for details.
[SRV] ℹ 77edf391-cb90-4176-ba4d-2e2f439e1e32 :: job-error :: OK
[RTE] ✔ complete workflow  77edf391-cb90-4176-ba4d-2e2f439e1e32
[RTE] ℹ {
  "id": "77edf391-cb90-4176-ba4d-2e2f439e1e32",
  "status": "running",
  "plan": {
    "id": "77edf391-cb90-4176-ba4d-2e2f439e1e32",
    "initialState": {},
    "start": "58f67ba4-e83d-4588-b4d1-aa5b826b0862",
    "jobs": [
      {
        "id": "f17f1718-dc2e-48e8-af14-1f994e9dc2b9",
        "next": {
          "58f67ba4-e83d-4588-b4d1-aa5b826b0862": true
        }
      },
      {
        "id": "58f67ba4-e83d-4588-b4d1-aa5b826b0862",
        "expression": "import { get } from \"@openfn/language-http\";\nexport * from \"@openfn/language-http\";\nexport default [get(\"https://www.google.com\")];",
        "adaptor": "@openfn/language-http@5.0.3"
      }
    ]
  },
  "threadId": 2,
  "startTime": 1699793531857,
  "duration": -1,
  "options": {}
}
[RTE] ❯ Purging workers
[SRV] ℹ 77edf391-cb90-4176-ba4d-2e2f439e1e32 :: attempt:log :: OK
[SRV] ℹ 77edf391-cb90-4176-ba4d-2e2f439e1e32 :: attempt:log :: OK
[SRV] ℹ 77edf391-cb90-4176-ba4d-2e2f439e1e32 :: attempt:log :: OK
[SRV] ℹ 77edf391-cb90-4176-ba4d-2e2f439e1e32 :: attempt:log :: OK
[SRV] ℹ 77edf391-cb90-4176-ba4d-2e2f439e1e32 :: attempt:log :: OK
[SRV] ℹ 77edf391-cb90-4176-ba4d-2e2f439e1e32 :: attempt:log :: OK
[SRV] ℹ 77edf391-cb90-4176-ba4d-2e2f439e1e32 :: attempt:complete :: OK
```

**Comment by josephjclark** [comment]
I can reproduce - here's the actual underlying error:
```
DOMException [DataCloneError]: function httpAdapter(config) {
  return new Promise(function dispatchHttpRequest(resolvePromise, rejectPromise)...<omitted>...
} could not be cloned.
    at new DOMException (node:internal/per_context/domexception:53:5)
    at worker.emit (/d/repo/openfn/kit/node_modules/.pnpm/workerpool@6.5.1/node_modules/workerpool/src/worker.js:252:12)
    at Object.workerEmit (/d/repo/openfn/kit/node_modules/.pnpm/workerpool@6.5.1/node_modules/workerpool/src/index.js:31:10)
    at publish (file:///d/repo/openfn/kit/packages/engine-multi/dist/worker/worker.js:49:14)
    at notify (file:///d/repo/openfn/kit/packages/engine-multi/dist/worker/worker.js:100:11)
    at file:///d/repo/openfn/kit/packages/runtime/dist/index.js:561:5
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Note to me: the current error reporting approach is hiding too much of this information from me.

**Comment by josephjclark** [comment]
This actually runs fine in the CLI.

It's something to do with serializing payloads across the worker boundary I think.
