### ISSUE TITLE
Linker: resolve to modules.exports

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/kit#523]
I think I've hit an issue deep in our module resolution in the runtime's linker (module loader).

## Repro Steps

Basically the sort-term symptom is: we can't do `import anyAscii from 'any-ascii';`. When trying to run the build adaptor through the CLI (and ditto the worker), you get this error:
```
/Users/openfn/Workspace/adaptors/packages/salesforce/dist/index.cjs:207
var import_any_ascii = __toESM(require("any-ascii"), 1);
                               ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/openfn/Workspace/adaptors/node_modules/.pnpm/any-ascii@0.3.2/node_modules/any-ascii/any-ascii.js from /Users/openfn/Workspace/adaptors/packages/salesforce/dist/index.cjs not supported.
Instead change the require of any-ascii.js in /Users/openfn/Workspace/adaptors/packages/salesforce/dist/index.cjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/openfn/Workspace/adaptors/packages/salesforce/dist/index.cjs:207:32)
    at async Promise.all (index 0)
    at async linker (file:///Users/openfn/.asdf/installs/nodejs/18.12.1/lib/node_modules/@openfn/cli/node_modules/@openfn/runtime/dist/index.js:202:19)
    at async file:///Users/openfn/.asdf/installs/nodejs/18.12.1/lib/node_modules/@openfn/cli/node_modules/@openfn/runtime/dist/index.js:279:22
    at async Promise.all (index 0)
    at async module_loader_default (file:///Users/openfn/.asdf/installs/nodejs/18.12.1/lib/node_modules/@openfn/cli/node_modules/@openfn/runtime/dist/index.js:277:3)
    at async prepareJob (file:///Users/openfn/.asdf/installs/nodejs/18.12.1/lib/node_modules/@openfn/cli/node_modules/@openfn/runtime/dist/index.js:397:21)
    at async file:///Users/openfn/.asdf/installs/nodejs/18.12.1/lib/node_modules/@openfn/cli/node_modules/@openfn/runtime/dist/index.js:362:35 {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.12.1
```

## What's Occurring

Tricky one to explain this.

In the runtime, the linker module will take a specifier like `any-ascii` and try to resolve it to a path in the repo. It does this by looking in the repo, finding the right module folder, reading the package.json, and looking for its entry point, as declared in `pkg.main`.

`any-ascii` is a pure ESM module which happens to use the `exports` property of package.json.

I think that because we don't parse exports, we don't resolve the module path properly, and so the module fails to load.

## And another thing

It looks like we're actually loading the CJS adaptor code here. Shouldn't we be loading the ESM format?

I have a feeling we're doing this to maintain parity with the old runtime. Or maybe old adaptors? But that doesn't seem necessary right now.

Alternatively we're not actually in control of this and for some reason node is choosing to use the CJS format.

It's probably something to do with adaptors - maybe we're using CJS because that's all the pre-monorepo adaptors support

**Comment by josephjclark** [comment]
I think this is nonsense. I think there's just something strange about any-ascii (or we have to do something special to load a pure esm module into cjs).

I say this because 1) we see the same error in core, which has very different module resolution, and 2) the runtime only resolves the _adaptor_ path. The adaptor's dependencies use native resolution.

Basically  I think `any-ascii` is incompatible with ESM.

**Comment by josephjclark** [comment]
I think this issue needs to change into: support ESM variants of adaptors when available. Which might be a monorepo thing.
